### ISSUE TITLE
Navigation buttons at bottom of page are reversed

### ISSUE THREAD

**Issue by magoorden** [Ecdar/www.ecdar.net#4]
At the bottom of a page, navigation buttons are present to go to the next or previous page. The order of these buttons feel counterintuitive for me.

We have the following situation on the [architecture](https://www.ecdar.net/architecture/) page:
![Screenshot 2022-06-07 at 09 24 58](https://user-images.githubusercontent.com/36483423/172321083-feefc435-3449-45f4-91f3-8911b7c04a4b.png)

To me, this suggest that Developers is the previous page and Download is the next one. In reality it is exactly the opposite, see the overal table of contents:

![Screenshot 2022-06-07 at 09 27 49](https://user-images.githubusercontent.com/36483423/172321341-ae2e3b18-02ad-48eb-b4c1-18f27e0bf433.png)

**Comment by yrke** [comment]
It seems there is a bug in the logic that swap the directions. Until we can get a fix in the theme i disabled the buttons
